# Site settings
title: Manju Priya Hari Krishnan's webpage
author: Manju Priya Hari Krishnan
email: h.manju91@yahoo.com
date: April 19, 2017
description: > # this means to ignore newlines until "baseurl:"
  A personal webpage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tenpercent.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
